# Generated by Django 4.0 on 2023-05-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine_html', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=15)),
                ('product', models.TextField()),
                ('date', models.CharField(max_length=15)),
            ],
        ),
    ]
